[package]
name = "std_mean"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
args = "1.0"  # Replace with the appropriate version for args
kornia = { workspace = true }
indicatif = { version = "0.17", features = ["rayon"] }
rayon = "1"
walkdir = "2"
