[package]
name = "webcam"
version = "0.1.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
args = "1.0.0"  # Replace with the appropriate version for args
ctrlc = "3.4.4"
kornia = { workspace = true, features = ["gstreamer"] }
rerun = { workspace = true }
